### ISSUE TITLE
Fails to build on Ubuntu 20.04

### ISSUE THREAD

**Issue by jtakeshi-nd** [nyetwurk/linux-wifi-88x2bu-driver#2]
`make ARCH=x86_64 CROSS_COMPILE= -C /lib/modules/5.8.0-50-generic/build M=/home/jonathan/Repositories/linux-wifi-88x2bu-driver  modules
make[1]: Entering directory '/usr/src/linux-headers-5.8.0-50-generic'
  CC [M]  /home/jonathan/Repositories/linux-wifi-88x2bu-driver/core/rtw_cmd.o
  CC [M]  /home/jonathan/Repositories/linux-wifi-88x2bu-driver/core/rtw_security.o
  CC [M]  /home/jonathan/Repositories/linux-wifi-88x2bu-driver/core/rtw_debug.o
  CC [M]  /home/jonathan/Repositories/linux-wifi-88x2bu-driver/core/rtw_io.o
In file included from /home/jonathan/Repositories/linux-wifi-88x2bu-driver/include/drv_types.h:78,
                 from /home/jonathan/Repositories/linux-wifi-88x2bu-driver/core/rtw_debug.c:17:
/home/jonathan/Repositories/linux-wifi-88x2bu-driver/include/rtw_security.h:252:8: error: redefinition of ‘struct sha256_state’
  252 | struct sha256_state {
      |        ^~~~~~~~~~~~
In file included from ./include/linux/filter.h:23,
                 from ./include/net/sock.h:59,
                 from ./include/linux/tcp.h:19,
                 from ./include/linux/ipv6.h:88,
                 from ./include/net/addrconf.h:50,
                 from /home/jonathan/Repositories/linux-wifi-88x2bu-driver/include/osdep_service_linux.h:48,
                 from /home/jonathan/Repositories/linux-wifi-88x2bu-driver/include/osdep_service.h:50,
                 from /home/jonathan/Repositories/linux-wifi-88x2bu-driver/include/drv_types.h:27,
                 from /home/jonathan/Repositories/linux-wifi-88x2bu-driver/core/rtw_debug.c:17:
./include/crypto/sha.h:84:8: note: originally defined here
   84 | struct sha256_state {
      |        ^~~~~~~~~~~~
In file included from /home/jonathan/Repositories/linux-wifi-88x2bu-driver/include/drv_types.h:78,
                 from /home/jonathan/Repositories/linux-wifi-88x2bu-driver/core/rtw_cmd.c:17:
/home/jonathan/Repositories/linux-wifi-88x2bu-driver/include/rtw_security.h:252:8: error: redefinition of ‘struct sha256_state’
  252 | struct sha256_state {
      |        ^~~~~~~~~~~~
In file included from ./include/linux/filter.h:23,
                 from ./include/net/sock.h:59,
                 from ./include/linux/tcp.h:19,
                 from ./include/linux/ipv6.h:88,
                 from ./include/net/addrconf.h:50,
                 from /home/jonathan/Repositories/linux-wifi-88x2bu-driver/include/osdep_service_linux.h:48,
                 from /home/jonathan/Repositories/linux-wifi-88x2bu-driver/include/osdep_service.h:50,
                 from /home/jonathan/Repositories/linux-wifi-88x2bu-driver/include/drv_types.h:27,
                 from /home/jonathan/Repositories/linux-wifi-88x2bu-driver/core/rtw_cmd.c:17:
./include/crypto/sha.h:84:8: note: originally defined here
   84 | struct sha256_state {
      |        ^~~~~~~~~~~~
In file included from /home/jonathan/Repositories/linux-wifi-88x2bu-driver/include/drv_types.h:78,
                 from /home/jonathan/Repositories/linux-wifi-88x2bu-driver/core/rtw_io.c:47:
/home/jonathan/Repositories/linux-wifi-88x2bu-driver/include/rtw_security.h:252:8: error: redefinition of ‘struct sha256_state’
  252 | struct sha256_state {
      |        ^~~~~~~~~~~~
In file included from ./include/linux/filter.h:23,
                 from ./include/net/sock.h:59,
                 from ./include/linux/tcp.h:19,
                 from ./include/linux/ipv6.h:88,
                 from ./include/net/addrconf.h:50,
                 from /home/jonathan/Repositories/linux-wifi-88x2bu-driver/include/osdep_service_linux.h:48,
                 from /home/jonathan/Repositories/linux-wifi-88x2bu-driver/include/osdep_service.h:50,
                 from /home/jonathan/Repositories/linux-wifi-88x2bu-driver/include/drv_types.h:27,
                 from /home/jonathan/Repositories/linux-wifi-88x2bu-driver/core/rtw_io.c:47:
./include/crypto/sha.h:84:8: note: originally defined here
   84 | struct sha256_state {
      |        ^~~~~~~~~~~~
In file included from /home/jonathan/Repositories/linux-wifi-88x2bu-driver/include/drv_types.h:78,
                 from /home/jonathan/Repositories/linux-wifi-88x2bu-driver/core/rtw_security.c:17:
/home/jonathan/Repositories/linux-wifi-88x2bu-driver/include/rtw_security.h:252:8: error: redefinition of ‘struct sha256_state’
  252 | struct sha256_state {
      |        ^~~~~~~~~~~~
In file included from ./include/linux/filter.h:23,
                 from ./include/net/sock.h:59,
                 from ./include/linux/tcp.h:19,
                 from ./include/linux/ipv6.h:88,
                 from ./include/net/addrconf.h:50,
                 from /home/jonathan/Repositories/linux-wifi-88x2bu-driver/include/osdep_service_linux.h:48,
                 from /home/jonathan/Repositories/linux-wifi-88x2bu-driver/include/osdep_service.h:50,
                 from /home/jonathan/Repositories/linux-wifi-88x2bu-driver/include/drv_types.h:27,
                 from /home/jonathan/Repositories/linux-wifi-88x2bu-driver/core/rtw_security.c:17:
./include/crypto/sha.h:84:8: note: originally defined here
   84 | struct sha256_state {
      |        ^~~~~~~~~~~~
/home/jonathan/Repositories/linux-wifi-88x2bu-driver/core/rtw_security.c:2191:13: error: conflicting types for ‘sha256_init’
 2191 | static void sha256_init(struct sha256_state *md)
      |             ^~~~~~~~~~~
In file included from ./include/linux/filter.h:23,
                 from ./include/net/sock.h:59,
                 from ./include/linux/tcp.h:19,
                 from ./include/linux/ipv6.h:88,
                 from ./include/net/addrconf.h:50,
                 from /home/jonathan/Repositories/linux-wifi-88x2bu-driver/include/osdep_service_linux.h:48,
                 from /home/jonathan/Repositories/linux-wifi-88x2bu-driver/include/osdep_service.h:50,
                 from /home/jonathan/Repositories/linux-wifi-88x2bu-driver/include/drv_types.h:27,
                 from /home/jonathan/Repositories/linux-wifi-88x2bu-driver/core/rtw_security.c:17:
./include/crypto/sha.h:136:20: note: previous definition of ‘sha256_init’ was here
  136 | static inline void sha256_init(struct sha256_state *sctx)
      |                    ^~~~~~~~~~~
make[2]: *** [scripts/Makefile.build:286: /home/jonathan/Repositories/linux-wifi-88x2bu-driver/core/rtw_security.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: *** [scripts/Makefile.build:286: /home/jonathan/Repositories/linux-wifi-88x2bu-driver/core/rtw_cmd.o] Error 1
make[2]: *** [scripts/Makefile.build:286: /home/jonathan/Repositories/linux-wifi-88x2bu-driver/core/rtw_io.o] Error 1
make[2]: *** [scripts/Makefile.build:286: /home/jonathan/Repositories/linux-wifi-88x2bu-driver/core/rtw_debug.o] Error 1
`

**Comment by terremoth** [comment]
Also fails here
ubuntu 20.04

`$ cat /var/lib/dkms/linux-wifi-88x2bu-driver/1.0/build/make.log`

```
DKMS make.log for linux-wifi-88x2bu-driver-1.0 for kernel 5.11.0-37-generic (x86_64)
qua 13 out 2021 16:47:18 -03
make ARCH=x86_64 CROSS_COMPILE= -C /lib/modules/5.11.0-37-generic/build M=/var/lib/dkms/linux-wifi-88x2bu-driver/1.0/build  modules
make[1]: Entrando no diretório '/usr/src/linux-headers-5.11.0-37-generic'
  CC [M]  /var/lib/dkms/linux-wifi-88x2bu-driver/1.0/build/core/rtw_cmd.o
  CC [M]  /var/lib/dkms/linux-wifi-88x2bu-driver/1.0/build/core/rtw_security.o
  CC [M]  /var/lib/dkms/linux-wifi-88x2bu-driver/1.0/build/core/rtw_debug.o
  CC [M]  /var/lib/dkms/linux-wifi-88x2bu-driver/1.0/build/core/rtw_io.o
  CC [M]  /var/lib/dkms/linux-wifi-88x2bu-driver/1.0/build/core/rtw_ioctl_query.o
  CC [M]  /var/lib/dkms/linux-wifi-88x2bu-driver/1.0/build/core/rtw_ioctl_set.o
  CC [M]  /var/lib/dkms/linux-wifi-88x2bu-driver/1.0/build/core/rtw_ieee80211.o
  CC [M]  /var/lib/dkms/linux-wifi-88x2bu-driver/1.0/build/core/rtw_mlme.o
  CC [M]  /var/lib/dkms/linux-wifi-88x2bu-driver/1.0/build/core/rtw_mlme_ext.o
  CC [M]  /var/lib/dkms/linux-wifi-88x2bu-driver/1.0/build/core/rtw_mi.o
  CC [M]  /var/lib/dkms/linux-wifi-88x2bu-driver/1.0/build/core/rtw_wlan_util.o
  CC [M]  /var/lib/dkms/linux-wifi-88x2bu-driver/1.0/build/core/rtw_vht.o
  CC [M]  /var/lib/dkms/linux-wifi-88x2bu-driver/1.0/build/core/rtw_pwrctrl.o
  CC [M]  /var/lib/dkms/linux-wifi-88x2bu-driver/1.0/build/core/rtw_rf.o
  CC [M]  /var/lib/dkms/linux-wifi-88x2bu-driver/1.0/build/core/rtw_recv.o
  CC [M]  /var/lib/dkms/linux-wifi-88x2bu-driver/1.0/build/core/rtw_sta_mgt.o
  CC [M]  /var/lib/dkms/linux-wifi-88x2bu-driver/1.0/build/core/rtw_ap.o
  CC [M]  /var/lib/dkms/linux-wifi-88x2bu-driver/1.0/build/core/mesh/rtw_mesh.o
  CC [M]  /var/lib/dkms/linux-wifi-88x2bu-driver/1.0/build/core/mesh/rtw_mesh_pathtbl.o
  CC [M]  /var/lib/dkms/linux-wifi-88x2bu-driver/1.0/build/core/mesh/rtw_mesh_hwmp.o
  CC [M]  /var/lib/dkms/linux-wifi-88x2bu-driver/1.0/build/core/rtw_xmit.o
  CC [M]  /var/lib/dkms/linux-wifi-88x2bu-driver/1.0/build/core/rtw_p2p.o
  CC [M]  /var/lib/dkms/linux-wifi-88x2bu-driver/1.0/build/core/rtw_rson.o
  CC [M]  /var/lib/dkms/linux-wifi-88x2bu-driver/1.0/build/core/rtw_tdls.o
  CC [M]  /var/lib/dkms/linux-wifi-88x2bu-driver/1.0/build/core/rtw_br_ext.o
  CC [M]  /var/lib/dkms/linux-wifi-88x2bu-driver/1.0/build/core/rtw_iol.o
  CC [M]  /var/lib/dkms/linux-wifi-88x2bu-driver/1.0/build/core/rtw_sreset.o
  CC [M]  /var/lib/dkms/linux-wifi-88x2bu-driver/1.0/build/core/rtw_btcoex_wifionly.o
  CC [M]  /var/lib/dkms/linux-wifi-88x2bu-driver/1.0/build/core/rtw_btcoex.o
  CC [M]  /var/lib/dkms/linux-wifi-88x2bu-driver/1.0/build/core/rtw_beamforming.o
  CC [M]  /var/lib/dkms/linux-wifi-88x2bu-driver/1.0/build/core/rtw_odm.o
  CC [M]  /var/lib/dkms/linux-wifi-88x2bu-driver/1.0/build/core/rtw_rm.o
  CC [M]  /var/lib/dkms/linux-wifi-88x2bu-driver/1.0/build/core/rtw_rm_fsm.o
  CC [M]  /var/lib/dkms/linux-wifi-88x2bu-driver/1.0/build/core/efuse/rtw_efuse.o
  CC [M]  /var/lib/dkms/linux-wifi-88x2bu-driver/1.0/build/os_dep/osdep_service.o
/var/lib/dkms/linux-wifi-88x2bu-driver/1.0/build/os_dep/osdep_service.c: In function ‘isFileReadable’:
/var/lib/dkms/linux-wifi-88x2bu-driver/1.0/build/os_dep/osdep_service.c:2189:11: error: implicit declaration of function ‘get_fs’; did you mean ‘get_sa’? [-Werror=implicit-function-declaration]
 2189 |   oldfs = get_fs();
      |           ^~~~~~
      |           get_sa
/var/lib/dkms/linux-wifi-88x2bu-driver/1.0/build/os_dep/osdep_service.c:2189:11: error: incompatible types when assigning to type ‘mm_segment_t’ {aka ‘struct <anonymous>’} from type ‘int’
/var/lib/dkms/linux-wifi-88x2bu-driver/1.0/build/os_dep/osdep_service.c:2190:3: error: implicit declaration of function ‘set_fs’; did you mean ‘sget_fc’? [-Werror=implicit-function-declaration]
 2190 |   set_fs(KERNEL_DS);
      |   ^~~~~~
      |   sget_fc
/var/lib/dkms/linux-wifi-88x2bu-driver/1.0/build/os_dep/osdep_service.c:2190:10: error: ‘KERNEL_DS’ undeclared (first use in this function); did you mean ‘KERNFS_NS’?
 2190 |   set_fs(KERNEL_DS);
      |          ^~~~~~~~~
      |          KERNFS_NS
/var/lib/dkms/linux-wifi-88x2bu-driver/1.0/build/os_dep/osdep_service.c:2190:10: note: each undeclared identifier is reported only once for each function it appears in
/var/lib/dkms/linux-wifi-88x2bu-driver/1.0/build/os_dep/osdep_service.c: In function ‘retriveFromFile’:
/var/lib/dkms/linux-wifi-88x2bu-driver/1.0/build/os_dep/osdep_service.c:2227:12: error: incompatible types when assigning to type ‘mm_segment_t’ {aka ‘struct <anonymous>’} from type ‘int’
 2227 |    oldfs = get_fs();
      |            ^~~~~~
/var/lib/dkms/linux-wifi-88x2bu-driver/1.0/build/os_dep/osdep_service.c:2228:11: error: ‘KERNEL_DS’ undeclared (first use in this function); did you mean ‘KERNFS_NS’?
 2228 |    set_fs(KERNEL_DS);
      |           ^~~~~~~~~
      |           KERNFS_NS
/var/lib/dkms/linux-wifi-88x2bu-driver/1.0/build/os_dep/osdep_service.c: In function ‘storeToFile’:
/var/lib/dkms/linux-wifi-88x2bu-driver/1.0/build/os_dep/osdep_service.c:2262:12: error: incompatible types when assigning to type ‘mm_segment_t’ {aka ‘struct <anonymous>’} from type ‘int’
 2262 |    oldfs = get_fs();
      |            ^~~~~~
/var/lib/dkms/linux-wifi-88x2bu-driver/1.0/build/os_dep/osdep_service.c:2263:11: error: ‘KERNEL_DS’ undeclared (first use in this function); did you mean ‘KERNFS_NS’?
 2263 |    set_fs(KERNEL_DS);
      |           ^~~~~~~~~
      |           KERNFS_NS
cc1: all warnings being treated as errors
make[2]: *** [scripts/Makefile.build:288: /var/lib/dkms/linux-wifi-88x2bu-driver/1.0/build/os_dep/osdep_service.o] Erro 1
make[1]: *** [Makefile:1849: /var/lib/dkms/linux-wifi-88x2bu-driver/1.0/build] Erro 2
make[1]: Saindo do diretório '/usr/src/linux-headers-5.11.0-37-generic'
make: *** [Makefile:1999: modules] Error 2
```

**Comment by kyp44** [comment]
Having the same issue, on linux kernel 5.13.0-51-generic.

**Comment by terremoth** [comment]
> Having the same issue, on linux kernel 5.13.0-51-generic.

I am using this repo: https://github.com/aircrack-ng/rtl8812au
it solved my problem, this repo is probably the only repo that actually works...
