### ISSUE TITLE
error: redefinition of ‘struct sha256_state’

### ISSUE THREAD

**Issue by nmix** [nyetwurk/linux-wifi-88x2bu-driver#1]
Hello

```bash
lsusb | grep TP
Bus 002 Device 004: ID 2357:012d TP-Link 802.11ac NIC

uname -v
#43~20.04.1-Ubuntu SMP Tue Jan 12 16:39:47 UTC 2021

# ... skipped previous commands

sudo dkms build -m linux-wifi-88x2bu-driver -v 1.0

Kernel preparation unnecessary for this kernel.  Skipping...

Building module:
cleaning build area...
'make' all KVER=5.8.0-38-generic...(bad exit status: 2)
ERROR (dkms apport): binary package for linux-wifi-88x2bu-driver: 1.0 not found
Error! Bad return status for module build on kernel: 5.8.0-38-generic (x86_64)
Consult /var/lib/dkms/linux-wifi-88x2bu-driver/1.0/build/make.log for more information.

cat /var/lib/dkms/linux-wifi-88x2bu-driver/1.0/build/make.log

DKMS make.log for linux-wifi-88x2bu-driver-1.0 for kernel 5.8.0-38-generic (x86_64)
Fri 15 Jan 2021 07:50:05 AM MSK
make ARCH=x86_64 CROSS_COMPILE= -C /lib/modules/5.8.0-38-generic/build M=/var/lib/dkms/linux-wifi-88x2bu-driver/1.0/build  modules
make[1]: Entering directory '/usr/src/linux-headers-5.8.0-38-generic'
  CC [M]  /var/lib/dkms/linux-wifi-88x2bu-driver/1.0/build/core/rtw_cmd.o
In file included from /var/lib/dkms/linux-wifi-88x2bu-driver/1.0/build/include/drv_types.h:78,
                 from /var/lib/dkms/linux-wifi-88x2bu-driver/1.0/build/core/rtw_cmd.c:17:
/var/lib/dkms/linux-wifi-88x2bu-driver/1.0/build/include/rtw_security.h:252:8: error: redefinition of ‘struct sha256_state’
  252 | struct sha256_state {
      |        ^~~~~~~~~~~~
In file included from ./include/linux/filter.h:23,
                 from ./include/net/sock.h:59,
                 from ./include/linux/tcp.h:19,
                 from ./include/linux/ipv6.h:88,
                 from ./include/net/addrconf.h:50,
                 from /var/lib/dkms/linux-wifi-88x2bu-driver/1.0/build/include/osdep_service_linux.h:48,
                 from /var/lib/dkms/linux-wifi-88x2bu-driver/1.0/build/include/osdep_service.h:50,
                 from /var/lib/dkms/linux-wifi-88x2bu-driver/1.0/build/include/drv_types.h:27,
                 from /var/lib/dkms/linux-wifi-88x2bu-driver/1.0/build/core/rtw_cmd.c:17:
./include/crypto/sha.h:84:8: note: originally defined here
   84 | struct sha256_state {
      |        ^~~~~~~~~~~~
make[2]: *** [scripts/Makefile.build:290: /var/lib/dkms/linux-wifi-88x2bu-driver/1.0/build/core/rtw_cmd.o] Error 1
make[1]: *** [Makefile:1780: /var/lib/dkms/linux-wifi-88x2bu-driver/1.0/build] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-5.8.0-38-generic'
make: *** [Makefile:1999: modules] Error 2
```

for Ubuntu 20.04 with Linux 5.4.0-58-generic compiles correctly

**Comment by nyetwurk** [comment]
I have moved to using https://github.com/cilynx/rtl88x2bu, will likely not do any further work in this repo :(

**Comment by nmix** [comment]
thanks
